#!/bin/bash
############ COLOR SECTION #############

# Reset
Off='\033[0m'       # Text Reset

# Regular Colors
Greenl='\033[1;32m'        # Green Light
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[1;36m'         # Cyan
White='\033[1;97m'        # White BOLD

########## END OF COLOR SECTION #########

function creates3bucket(){
read -p "Enter a desired s3 bucket name: " bucketName
if aws s3api head-bucket --bucket "$bucketName" 2>/dev/null
	then
		echo "The bucket is already exists!!"
    else
		echo "The bucket doesnt exists and will be created now!"
		read -p "enter a region name in format (us-west-1): " regionName
		aws s3api create-bucket --bucket "$bucketName" --create-bucket-configuration LocationConstraint=$regionName
		echo "Bucket $bucketName was created! Use it!"
fi
}

function listAllBuckets() {
echo "These are youre buckets already exists!"
aws s3 ls
}

function uploads3file() {
read -p "Enter the local file names separated by comma - ,: " fileNames
IFS=',' read -ra files <<< "$fileNames"
read -p "Enter the S3 bucket name: " bucketName
for file in "${files[@]}" 
	do
		aws s3 cp "$file" "s3://$bucketName/"
		echo "File $file uploaded successfully!"
	done
}

 

function downloads3file() {
read -p "Enter the remote file name: " fileNames
IFS=',' read -ra files <<< "$fileNames"
read -p "Enter the S3 bucket name: " bucketName
for file in "${files[@]}" 
	do
		aws s3 cp  "s3://$bucketName/$file" .
		echo "File $file downloaded successfully!"
	done
}

 

 

function deletes3file() {
read -p "Enter the remote file names separated by comma - ,: " fileNames
IFS=',' read -ra files <<< "$fileNames"
read -p "Enter the S3 bucket name: " bucketName
for file  in "${files[@]}" 
	do
		aws s3 rm s3://$bucketName/$file
		echo "File $file deleted successfully!"
	done
}

 

function lists3bucket() {
echo "Let list all files in specific bucket!"
read -p "Enter the S3 bucket name: " bucketName
aws s3 ls s3://$bucketName/
}


function s3tos3() {
echo "Lets copy files from one s3 bucket to another s3 bucket"
read -p "Enter the S3 bucket name you want copy from: " bucketNameFrom
read -p "Enter the S3 bucket name you want copy to: " bucketNameTo
read -p "Enter the file names separated by comma - ,: " fileNames
IFS=',' read -ra files <<< "$fileNames"
for file in "${files[@]}" 
	do
		aws s3 cp  "s3://$bucketNameFrom/$file" "s3://$bucketNameTo"
		echo -e "File $file copied successfully! from bucket ${Green}$bucketNameFrom${Off} to bucket ${Red}$bucketNameTo${Off}"
	done
}

function s3deleteBucket() {
echo "Note! The deleting of the bucket can't be undone!!"
read -p "Are you ready to loss all your data in specific bucket? y/n " lossData
	if [[ $lossData = "y" ]]
		then
			read -p "Enter a name of a bucket to check if it empty to delete it: " bucketName
			echo "These are files in your bucket: "
			echo "---------------------------------------------------------------------------------"
			aws s3 ls s3://$bucketName
			echo "---------------------------------------------------------------------------------"
			read -p "Are you sure you wanna to empty your bucket? y/n " emptyB
				if [[ $emptyB = "y" ]]
					then
						echo "Removing all files!"
						sleep 3
						aws s3 rm s3://$bucketName --recursive
						read -p "Well done, all data is cleaned\nAre you sure you wanna to delete your bucket $bucketName finally y/n? " s3buckketdelFin
						if [[ $s3buckketdelFin = "y" ]]
							then
								echo "Removing your bucket $bucketName"
								sleep 3
								aws s3 rb s3://$bucketName
						fi
				fi
	fi
echo "Your bucket $bucketName successfully deleted!"
}

############ START MAIN SECTION ################

function main() {
while :
	do
		echo -e "\n\n\n***************************"
		echo          "***************************"
		echo          "MAKE YOUR CHOISE RIGHT NOW!"
		echo          "***************************"
		echo          "***************************"

			 echo -e "1. ${Yellow}Upload a file${Off}"
			 echo -e "2. ${Green}Download file${Off}"
			 echo -e "3. ${Red}Delete a file${Off}"
			 echo -e "4. ${Cyan}List all files${Off}"
			 echo -e "5. ${Blue}Create S3 BUCKET${Off}"
			 echo -e "6. ${Purple}List all existing buckets${Off}"
			 echo -e "7. ${Greenl}Copy from bucket to bucket${Off}"
			 echo -e "8. ${White}Quit${Off}"
			 echo -e "9. ${}Delete bucket"


		read -p "take your choice: " choice
		case $choice in
 
			1) uploads3file ;;
			2) downloads3file ;;
			3) deletes3file ;;
			4) lists3bucket ;;
			5) creates3bucket ;;
			6) listAllBuckets ;;
			7) s3tos3 ;;
			8) break ;;
			*) echo "nums from 1 to 8 ONLY" ; sleep 3 ;;
		esac
	done
}




main
############ END MAIN SECTION ################
