#!/bin/bash
############ COLOR SECTION #############

# Reset
Off='\033[0m'       # Text Reset

# Regular Colors
Greenl='\033[1;32m'        # Green Light
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[1;36m'         # Cyan
White='\033[1;97m'        # White BOLD

########## END OF COLOR SECTION #########

function creates3bucket(){
read -p "Enter a desired s3 bucket name: " bucketName
if aws s3api head-bucket --bucket "$bucketName" 2>/dev/null
	then
		echo "The bucket is already exists!!"
    else
		echo "The bucket doesnt exists and will be created now!"
		read -p "enter a region name in format (us-west-1): " regionName
		aws s3api create-bucket --bucket "$bucketName" --create-bucket-configuration LocationConstraint=$regionName
		echo "Bucket $bucketName was created! Use it!"
fi
}

function listAllBuckets() {
echo "These are youre buckets already exists!"
aws s3 ls
}

function uploads3file() {
read -p "Enter the local file names separated by comma - ,: " fileNames
IFS=',' read -ra files <<< "$fileNames"
read -p "Enter the S3 bucket name: " bucketName
for file in "${files[@]}" 
	do
		aws s3 cp "$file" "s3://$bucketName/"
		echo "File $file uploaded successfully!"
	done
}

 

function downloads3file() {
read -p "Enter the remote file name: " fileNames
IFS=',' read -ra files <<< "$fileNames"
read -p "Enter the S3 bucket name: " bucketName
for file in "${files[@]}" 
	do
		aws s3 cp  "s3://$bucketName/$file" .
		echo "File $file downloaded successfully!"
	done
}

 

 

function deletes3file() {
read -p "Enter the remote file names separated by comma - ,: " fileNames
IFS=',' read -ra files <<< "fileNames"
read -p "Enter the S3 bucket name: " bucketName
for file  in "${files[@]}" 
	do
		aws s3 rm s3://$bucketName/$file
		echo "File $file deleted successfully!"
	done
}

 

function lists3bucket() {
echo "Let list all files in specific bucket!"
read -p "Enter the S3 bucket name: " bucketName
aws s3 ls s3://$bucketName/
}

 



############ START MAIN SECTION ################

function main() {
while :
	do
		echo -e "\n\n\n***************************"
		echo          "***************************"
		echo          "MAKE YOUR CHOISE RIGHT NOW!"
		echo          "***************************"
		echo          "***************************"

			 echo -e "1. ${Yellow}Upload a file${Off}"
			 echo -e "2. ${Green}Download file${Off}"
			 echo -e "3. ${Red}Delete a file${Off}"
			 echo -e "4. ${Cyan}List all files${Off}"
			 echo -e "5. ${Blue}Create S3 BUCKET${Off}"
			 echo -e "6. ${Purple}List all existing buckets${Off}"
			 echo -e "7. ${White}Quit${Off}"


		read -p "take your choice: " choice
		case $choice in
 
			1) uploads3file ;;
			2) downloads3file ;;
			3) deletes3file ;;
			4) lists3bucket ;;
			5) creates3bucket ;;
			6) listAllBuckets ;;
			7) break ;;
			*) echo "nums from 1 to 6 ONLY" ; sleep 3 ;;
		esac
	done
}




main
############ END MAIN SECTION ################
