#!/bin/bash

function creates3bucket(){
read -p "Enter a desired s3 bucket name: " bucketName
if aws s3api head-bucket --bucket "$bucketName" 2>/dev/null
	then
		echo "The bucket is already exists!!"
    else
		echo "The bucket doesnt exists and will be created now!"
		read -p "enter a region name in format (us-west-1): " regionName
		aws s3api create-bucket --bucket "$bucketName" --create-bucket-configuration LocationConstraint=$regionName
		echo "Bucket $bucketName was created! Use it!"
fi
}

function listAllBuckets() {
echo "These are youre buckets already exists!"
aws s3 ls
}

function uploads3file() {
read -p "Enter the local file name: " fileName
read -p "Enter the S3 bucket name: " bucketName
aws s3 cp $fileName s3://$bucketName/
}

 

function downloads3file() {
read -p "Enter the remote file name: " fileName
read -p "Enter the S3 bucket name: " bucketName
aws s3 cp s3://$bucketName/$fileName .
}

 

 

function deletes3file() {
read -p "Enter the remote file name: " fileName
read -p "Enter the S3 bucket name: " bucketName
aws s3 rm s3://$bucketName/$fileName
}

 

function lists3bucket() {
read -p "Enter the S3 bucket name: " bucketName
aws s3 ls s3://$bucketName/
}

 



############ START MAIN SECTION ################

function main() {
while :
	do
		echo -e "\n\n\n***************************"
		echo          "***************************"
		echo          "MAKE YOUR CHOISE RIGHT NOW!"
		echo          "***************************"
		echo          "***************************"

			 echo "1. Upload a file "
			 echo "2. Download file"
			 echo "3. Delete a file"
			 echo "4. List all files"
			 echo "5. Create S3 BUCKET"
			 echo "6. list all existing buckets"
			 echo "7. Quit"


		read -p "take your choice: " choice
		case $choice in
 
			1) uploads3file ;;
			2) downloads3file ;;
			3) deletes3file ;;
			4) lists3bucket ;;
			5) creates3bucket ;;
			6) listAllBuckets ;;
			7) break ;;
			*) echo "nums from 1 to 6 ONLY" ; sleep 3 ;;
		esac
	done
}




main
############ END MAIN SECTION ################
